### ISSUE TITLE
Docker Build Fails on ARM v7

### ISSUE THREAD

**Issue by abuaboud** [ewfian/faiss-node#44]
**Environment:**
 - Operating System: Linux/arm/v7
 - Node.js Version: 18.7.1
 - Package Version: 0.5.0

I'm using the `node:18.17.1-bullseye` image to create an image for different types of computers, including armv7, amd64, and arm64. To get the necessary stuff, I'm running `apt update && apt install -y cmake libopenblas-dev patchelf`.

This setup works well for arm64 and amd64 computers, but it's not working right for the armv7 computer. You can see the full error message here: [GitHub Action Run](https://github.com/activepieces/activepieces/actions/runs/6362212763/job/17277106133).

Here's the error message for the armv7 computer:

```
#29 70.21 npm ERR! CMake Error at CMakeLists.txt:51 (add_subdirectory):
#29 70.21 npm ERR!   add_subdirectory given source "deps/faiss" which is not an existing
#29 70.21 npm ERR!   directory.
#29 70.21 npm ERR! 
#29 70.21 npm ERR! 
#29 70.21 npm ERR! CMake Error at CMakeLists.txt:52 (set_target_properties):
#29 70.21 npm ERR!   set_target_properties Can not find target to add properties to: faiss
#29 70.21 npm ERR! 
#29 70.21 npm ERR! 
#29 70.21 npm ERR! Debian:aarch64
#29 70.21 npm ERR! Copy DEPENDANCES: /lib/aarch64-linux-gnu/libgomp.so.1
#29 70.21 npm ERR! Copy DEPENDANCES: /lib/aarch64-linux-gnu/libopenblas.so.0
#29 70.21 npm ERR! Copy DEPENDANCES: /lib/aarch64-linux-gnu/libgfortran.so.5
#29 70.21 npm ERR! ERR! OMG Process terminated: 1
```

I'm looking for ideas on how to make it work properly on the ARM/v7, Can you guide me where i should be looking at?

**Comment by ewfian** [comment]
@abuaboud  This is because the source code of the dependent faiss does not exist.

Will fix this issue  by adding following line into `install` hook of `package.json`

git clone -b v1.7.4 --depth 1 https://github.com/facebookresearch/faiss.git deps/faiss

<img width="1264" alt="image" src="https://github.com/ewfian/faiss-node/assets/12423122/6a0a576e-c1a8-4221-8c68-36def83df739">

As a temporary workaround, you can try to clone the faiss source code to the faiss-node directory before installing.

**Comment by ewfian** [comment]
And you will also needs `git` pre-installed. See: https://github.com/ewfian/faiss-node/pull/45/commits/0fb2a78df548187bb4d4efdf521c00d049b423a5

**Comment by ewfian** [comment]
@abuaboud  New version (0.5.1) just released
